### ISSUE TITLE
MNIST for beginners page uses old API in code

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j-docs#100]
https://deeplearning4j.org/mnist-for-beginners

```.regularization(true)```
```.activation("softmax")``` 

## Due Date
*To be completed by:* YYYY-MM-DD

## Description
*Write a short description of what needs to be done.*

## Assignees
*Please ensure you have assigned at least one person to this issue. Include any authors and reviewers required.*

**Comment by ejunprung** [comment]
I think we re-did this tutorial so I'll close this issue. This looks like the new one: https://deeplearning4j.org/tutorials/00-quickstart-for-deeplearning4j
