### ISSUE TITLE
Arbiter Autogen

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j-docs#102]
Write autogen docs for Arbiter in the main monorepo.

**Comment by eraly** [comment]
I wrote the content in a google doc for now.
I'd like @AlexDBlack to give it a quick pass.
https://docs.google.com/document/d/1-uzzp2LT8Qqru-F3dJGqy0F4TZbGkEjAQctEnU9PaMU/edit?usp=sharing

**Comment by eraly** [comment]
FYI: I haven't fixed formatting and general phrasing in doc above. It will look nice when I get it done in markdown. Looking for feedback on content.

**Comment by eraly** [comment]
Alex reviewed and I also made changes to reflect the most recent updates. Now need to get this into auto docs.

**Comment by eraly** [comment]
Justin is generating autodocs.

**Comment by crockpotveggies** [comment]
https://deeplearning4j.org/docs/latest/arbiter-overview
