### ISSUE TITLE
Important content from old website

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j-docs#113]
Here's a (possibly incomplete) list of pages that had good content that we might want to keep (though some need an update pass).
There was a ton of important info there that I don't think we have replacements for yet.

* /quickref (https://github.com/deeplearning4j/deeplearning4j-docs/issues/112)
* /snapshots
* /workspaces
* ~~/cudnn~~ (I've reuploaded this - Alex)
* /android

## Due Date
*To be completed by:* YYYY-MM-DD

## Description
*Write a short description of what needs to be done.*

## Assignees
*Please ensure you have assigned at least one person to this issue. Include any authors and reviewers required.*

**Comment by crockpotveggies** [comment]
Android has been reuploaded and cuDNN was migrated to autogen. In the future please put docs content in the main repo, and run autogen and update the user guide. Updated the README to make it more clear.

**Comment by crockpotveggies** [comment]
workspaces https://deeplearning4j.org/docs/latest/deeplearning4j-config-workspaces

**Comment by crockpotveggies** [comment]
Quickref cheat sheet: https://deeplearning4j.org/docs/latest/deeplearning4j-cheat-sheet
...only thing left is Snapshots
note there's build from source: https://deeplearning4j.org/docs/latest/deeplearning4j-build-from-source

**Comment by AlexDBlack** [comment]
Snapshots: https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots (no redirect from /snapshots though, not sure if we want to add that)
I think that's it? We can open a separate issue if we discover anything else missing....
