### ISSUE TITLE
NLP Doc links returns 404

### ISSUE THREAD

**Issue by rahul-raj** [deeplearning4j/deeplearning4j-docs#121]
There are more instances, but at the moment I have only these:
https://deeplearning4j.org/programmingguide/07_nlp
https://deeplearning4j.org/nlp

Unable to find respective skymind pages as well.

**Comment by crockpotveggies** [comment]
Our new NLP page is here: https://deeplearning4j.org/docs/latest/deeplearning4j-nlp-overview

The programming guide will make a return in the future. It currently requires lots of updating, and meanwhile the user guide is more up-to-date.
