### ISSUE TITLE
Add redirects (or fix gitterbot?) links

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j-docs#122]
Most of our Gitterbot links are broken since the new website launch.

What's the plan? Fix the links (redirects etc) or fix gitterbot?
I'd be in favor of the former (these short links are nice, especially for chat)

https://deeplearning4j.org/troubleshootingneuralnets
https://deeplearning4j.org/visualization
https://deeplearning4j.org/cudnn
https://deeplearning4j.org/memory
https://deeplearning4j.org/documentation
https://deeplearning4j.org/modelpersistence
https://deeplearning4j.org/evaluation
https://deeplearning4j.org/quickref

**Comment by crockpotveggies** [comment]
Forwards have been put in place.
