### ISSUE TITLE
Max-width on images

### ISSUE THREAD

**Issue by ejunprung** [deeplearning4j/deeplearning4j-docs#123]
Some screenshots are too large, rendering beyond the screen. 

Example: https://deeplearning4j.org/docs/latest/deeplearning4j-nn-visualization

**Comment by AlexDBlack** [comment]
Also:
https://deeplearning4j.org/docs/latest/deeplearning4j-quickstart (only mildly)
https://deeplearning4j.org/docs/latest/deeplearning4j-nn-recurrent
https://deeplearning4j.org/docs/latest/deeplearning4j-nn-tsne-visualization

**Comment by ejunprung** [comment]
I've fixed this issue.
