### ISSUE TITLE
DL4J Release Notes

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j-docs#13]
## Due Date
*To be completed by:* 2018-04-30

## Description
Update docs for release notes on v1.0

## Assignees
*Please ensure you have assigned at least one person to this issue. Include any authors and reviewers required.*

**Comment by crockpotveggies** [comment]
https://github.com/deeplearning4j/deeplearning4j-docs/pull/12

**Comment by crockpotveggies** [comment]
https://github.com/deeplearning4j/deeplearning4j-docs/pull/11

**Comment by crockpotveggies** [comment]
https://github.com/deeplearning4j/deeplearning4j-docs/pull/16

**Comment by AlexDBlack** [comment]
One page that needs updating after the release: the quickref page... it still references snapshots (note also the bold/italics stuff)
https://deeplearning4j.org/quickref

Maybe also do a quick check of the change log/release notes to make sure all the new stuff is there.
https://deeplearning4j.org/releasenotes

Note also a bunch of the DataSetIterator (Iterators section) links on the quickref page were broken by recent source code refactoring soon before the release. They are all now under deeplearning4j-data:
https://github.com/deeplearning4j/deeplearning4j/tree/master/deeplearning4j-data

Edit: oh, and javadoc needs updating: https://github.com/SkymindIO/skymind-docs/issues/148

Edit 2: https://deeplearning4j.org/cudnn still references CUDA 7.5 (no longer available on 1.0.0-alpha). We support 8.0, 9.0 and 9.1 now. Maybe emphasize cuda 9.1 in the docs, as it's the latest (i.e., there's no reason to use an earier version, unless that's what you already have installed).

**Comment by saudet** [comment]
FYI I've done my updates for cudnn.md and in releasenotes.md for RL4J!

**Comment by crockpotveggies** [comment]
@AlexDBlack confirming all of the DL4J release notes are updated?

**Comment by AlexDBlack** [comment]
Yeah, release notes are probably good as is. Some more detail on ND4J might be nice (bug fixes etc) but isn't strictly required; only thing that we might want is some stuff on Jumpy? (@farizrahman4u was mentioned in dev channel in context of that, no idea if there's anything to add or not though).

As for the other stuff I've mentioned in my last comment - quickref, broken links, javadoc, cudnn pages - they are AFAIK still outstanding. Perhaps they can get new/separate issues.
Oh, and we've got a few new examples might want to be mentioned here? https://deeplearning4j.org/examples-tour

**Comment by crockpotveggies** [comment]
All new issues have been created. Closing this one.
