### ISSUE TITLE
CuDNN page is out of date

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j-docs#154]
https://deeplearning4j.org/docs/latest/deeplearning4j-config-cudnn
Lists CUDA 8 support and lacks CUDA 10 support for 1.0.0-beta3.
Also doesn't recommend a CUDNN version for CUDA 10.

A separate issue that might be fixed at the same time: No mention of the -redist artifacts.

## Due Date
*To be completed by:* YYYY-MM-DD

## Description
*Write a short description of what needs to be done.*

## Assignees
*Please ensure you have assigned at least one person to this issue. Include any authors and reviewers required.*

**Comment by saudet** [comment]
I've updated the docs for Android and cuDNN in commit https://github.com/deeplearning4j/deeplearning4j/commit/d328c7e385e316f6fd84211d8270a6fe74249e18. The redist artifacts do get mentioned, looks good?

**Comment by AlexDBlack** [comment]
@saudet LGTM, thanks!
