### ISSUE TITLE
Keras import supported features is missing checkboxes

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/deeplearning4j-docs#167]
https://deeplearning4j.org/docs/latest/keras-import-supported-features

see here, we previously had checkboxes, which are gone now. this can be misleading. e.g. it looks like we have GRU etc., but we don't.

**Comment by ejunprung** [comment]
@maxpumperla Do you happen to have a copy of the original? I'll add the checkboxes back in but I'm not sure which items should be checked/unchecked.

**Comment by maxpumperla** [comment]
@ejunprung sure, it's here: https://github.com/deeplearning4j/deeplearning4j/blob/master/docs/keras-import/templates/supported-features.md

if you click on "Raw" you'll see which items are `<i class="fa fa-check-square-o">` (checked) and which are `<i class="fa fa-square-o">` (unchecked). thanks!

**Comment by ejunprung** [comment]
@maxpumperla Okay, fixed. I made the unchecked square a red "X" if you are okay with that. I'll create a pull request once Justin fixes the auto-gen stuff. 

<img width="930" alt="screen shot 2019-02-16 at 9 04 25 pm" src="https://user-images.githubusercontent.com/5703667/52908683-691ef900-322f-11e9-8952-0686dd6a9041.png">

**Comment by maxpumperla** [comment]
@ejunprung awesome, thanks. looks pretty good.

Just to be sure, the next time someone updates content from the autogen script, will your style changes be kept? i.e. did you manipulate the markdown file or just style sheets etc.?

**Comment by ejunprung** [comment]
@maxpumperla Yup, the styles will be kept. I made a small update to supported-features.md (no changes to the stylesheet).

**Old:** <i class="fa fa-check-square-o"></i>
**New:** <i class="far fa-check-square"></i>

As you can see, the classes are different in the new version of Font Awesome. When we migrated to the new DL4J docs template, we pointed to the new version of Font Awesome so the old classes were no longer valid. 

From what I understand, the autogen script dynamically inserts content into the markdown files (e.g. Javadoc classes). Still have to manually edit content to make changes so stuff won't get overwritten or anything like that.

**Comment by crockpotveggies** [comment]
This appears to be fixed as per screenshot. Closing.

<img width="877" alt="Screen Shot 2019-05-28 at 3 47 57 PM" src="https://user-images.githubusercontent.com/1445295/58517373-07402a80-8160-11e9-8059-76291ab1a97f.png">
