### ISSUE TITLE
Some documentation has broken links

### ISSUE THREAD

**Issue by wbrege** [deeplearning4j/deeplearning4j-docs#177]
## Description
Some of the links on your website are broken. EG: https://deeplearning4j.org/tutorials/01-multilayernetwork-and-computationgraph the follow up tutorial links at the bottom just take you to "someurl"

**Comment by crockpotveggies** [comment]
Performed a pass on the tutorials and I cleaned up some broken links. Thank you for identifying this, I believe it is fixed. If you find anything else you are welcome to open a new issue.
