### ISSUE TITLE
Update website Javadoc for 1.0.0-beta release

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j-docs#26]
Adding this issue so it doesn't get forgotten. Feel free to close/combine/edit as required.

We need to update the javadoc for DL4J and ND4J given the 1.0.0-alpha release.
https://deeplearning4j.org/doc/
https://nd4j.org/doc/

While we are at it: I don't believe we've ever had javadoc online for:
- DataVec
- Arbiter
- RL4J

It wouldn't hurt to get javadoc for these up also.

**Comment by crockpotveggies** [comment]
Waiting on merging of https://github.com/deeplearning4j/deeplearning4j/pull/4900 which also currently affects benchmarks of v1.0.0

**Comment by AlexDBlack** [comment]
Can we get the javadoc updated for 1.0.0-beta?
The javadoc was last updated on 2 April 2017... more than 13 months ago :/

**Comment by AlexDBlack** [comment]
DL4J and DataVec done
RL4J and ND4J remain at old versions (0.8.0 I think)

**Comment by crockpotveggies** [comment]
With new monorepo it should all be here? https://deeplearning4j.org/api/latest/
