### ISSUE TITLE
Remove "Other Machine Learning Tutorials" from Keras page

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j-docs#44]
The section at the end of the page doesn't really belong here...
https://deeplearning4j.org/keras-supported-features#other-machine-learning-tutorials

## Due Date
*To be completed by:* YYYY-MM-DD

## Description
*Write a short description of what needs to be done.*

## Assignees
*Please ensure you have assigned at least one person to this issue. Include any authors and reviewers required.*

**Comment by crockpotveggies** [comment]
This has been addressed in the documentation overhaul.
