### ISSUE TITLE
Styles Missing on MNIST For Beginners Page

### ISSUE THREAD

**Issue by ejunprung** [deeplearning4j/deeplearning4j-docs#45]
Take a look at https://deeplearning4j.org/mnist-for-beginners

**Comment by crockpotveggies** [comment]
@ejunprung this was actually a problem created by you. for future reference, be careful when using file extensions. You had renamed it to `.html` instead of keeping `.md`.

**Comment by ejunprung** [comment]
@crockpotveggies Ah, I forgot about that. 

"mnist-for-beginners" should actually be `.html`. I did this because I wanted to use the default "Table of Contents" styles provided by the theme. If I remember correctly, `.md` doesn't permit that. Might have been a bad idea but it was intentional. 

I can refactor the page if we want consistency. Just tell me if that is preferred and I'll take a look next week.

**Comment by crockpotveggies** [comment]
You won't be able to style the page with .html and if you simply want to
add HTML to the .md files you can write HTML inside of them.

All pages should be in .md unless you don't need any themes.

**Comment by crockpotveggies** [comment]
100% you can mix MD and HTML. It's great :)
