### ISSUE TITLE
Links in documentation pointing to non existing resources

### ISSUE THREAD

**Issue by Bentipe** [deeplearning4j/deeplearning4j-docs#55]
## Description
Documentation on official web page has broken links that point to github, 2 detected here.
On the end of the section the link that points to the code on github:
https://deeplearning4j.org/deepautoencoder#code-sample

For this first point Paul Dubs @treo commented on gitter the following:
> But as RBMs have been removed, you not find any examples on them anyway. So that doc should be updated and the code sample there should be removed

On the end of the overview section, the link that points to ParallelWrapper:
https://deeplearning4j.org/spark

**Comment by crockpotveggies** [comment]
Thanks for reporting this! We will get this taken care of before our full release of 1.1.0.

**Comment by wmeints** [comment]
Also note that the autoencoder docs describe `RBM` which is no longer available.

**Comment by crockpotveggies** [comment]
@eraly can you help get this fixed?

**Comment by eraly** [comment]
Sure.

**Comment by eraly** [comment]
I've scrubbed all github links.
