### ISSUE TITLE
Broken links and images on docs

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j-docs#95]
This issue has been migrated from https://github.com/deeplearning4j/deeplearning4j/issues/5877

Original author @rahul-raj

----

Post: [https://skymind.ai/wiki/lstm.html](https://skymind.ai/wiki/lstm.html) has lots of broken images to fix for:
https://skymind.ai/wiki/img/lstm_gru.png
https://skymind.ai/wiki/img/feedforward_rumelhart.png
https://skymind.ai/wiki/img/gates_lstm.png
https://skymind.ai/wiki/img/recurrent_equation.png
https://skymind.ai/wiki/img/greff_lstm_diagram.png
https://skymind.ai/wiki/img/gers_lstm.png
https://skymind.ai/wiki/img/sigmoid_vanishing_gradient.png
https://skymind.ai/wiki/img/srn_elman.png

**Comment by rahul-raj** [comment]
The images are perfectly working at github docs directory:
https://github.com/deeplearning4j/deeplearning4j-docs/blob/gh-pages/lstm.md

Only live docs having the issue.

**Comment by crockpotveggies** [comment]
Live doc images now work: https://deeplearning4j.org/docs/latest/deeplearning4j-quickstart
